import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {chromium,chrome,base,safePage} from './qa-runtime.mjs';
const out=path.resolve('review',process.argv[2]||'final-v1');fs.mkdirSync(out,{recursive:true});const reports=[];
const browser=await chromium.launch({executablePath:chrome,headless:true});
const snapshot=()=>({y:scrollY,docHeight:document.documentElement.scrollHeight,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,layers:[...document.querySelectorAll('.stochastic-layer[data-depth]')].map(e=>{const s=getComputedStyle(e),b=e.getBoundingClientRect(),m=new DOMMatrixReadOnly(s.transform==='none'?undefined:s.transform),world=e.closest('[data-stochastic-global]');return {name:e.className,depth:Number(e.dataset.depth),global:Boolean(world),transform:s.transform,x:m.m41,y:m.m42,opacity:s.opacity,display:s.display,width:b.width,height:b.height,worldPosition:getComputedStyle(e.parentElement).position};})});
for(const route of (process.argv[3]?[process.argv[3]]:['index.html','thinking-in-measures.html']))for(const [mode,width,height,motion,js] of [['desktop',1440,1000,'no-preference',true],['phone',390,844,'no-preference',true],['compact',360,800,'no-preference',true],['reduced',390,844,'reduce',true],['nojs',390,844,'reduce',false]].filter(s=>!process.argv[4]||process.argv[4].split(',').includes(s[0]))) {
 const name=(route==='index.html'?'home':'reader')+'-'+mode;const reader=route!=='index.html';const page=await safePage(browser,{viewport:{width,height},deviceScaleFactor:1,reducedMotion:motion,javaScriptEnabled:js,hasTouch:width<500,isMobile:width<500});
 const r={name,route,width,height,motion,js,errors:[],failed:[],httpErrors:[],resources:[]};page.on('pageerror',e=>r.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});page.on('requestfailed',q=>r.failed.push({url:q.url(),failure:q.failure()}));page.on('response',q=>{r.resources.push(q.url());if(q.status()>=400)r.httpErrors.push({url:q.url(),status:q.status()});});
 await page.goto(base+route,{waitUntil:'domcontentloaded',timeout:60000});await page.evaluate(()=>document.fonts.ready);if(js)await page.waitForSelector('html.sc-ready');
 if(reader&&js){await page.waitForSelector('.blog-card');await page.waitForSelector('body[data-math-ready="true"]',{timeout:30000});await page.evaluate(()=>window.__timMathReady);}
 await page.waitForTimeout(500);
 r.initial=await page.evaluate(()=>({title:document.title,scrollWidth:document.documentElement.scrollWidth,width:innerWidth,height:document.documentElement.scrollHeight,engine:window.ScrollCraft?.instances?.length||0,bodyBackground:getComputedStyle(document.body).backgroundColor,images:[...document.images].map(i=>({src:i.currentSrc,loaded:i.complete&&i.naturalWidth>0})),math:document.querySelectorAll('mjx-container').length,mathErrors:document.querySelectorAll('mjx-merror,[data-mjx-error]').length,notes:document.querySelectorAll('.blog-toggle-btn').length,fallbacks:[...document.querySelectorAll('.reading-fallback a')].map(a=>a.getAttribute('href')),referencesVisible:[...document.querySelectorAll('.module-references')].filter(e=>e.getBoundingClientRect().height>0).length,missingAnchors:[...document.querySelectorAll('a[href^="#"]')].map(e=>e.getAttribute('href')).filter(h=>h.length>1&&!document.getElementById(h.slice(1)))}));
 await page.screenshot({path:path.join(out,name+'-opening.png')});r.layers=[];
 const heroHeight=await page.locator('.masthead').evaluate(e=>e.offsetHeight);
 for(const fraction of [0,.2,.5,.8]){await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),Math.round(heroHeight*fraction));await page.waitForTimeout(240);r.layers.push(await page.evaluate(snapshot));if(mode==='desktop'||mode==='phone')await page.screenshot({path:path.join(out,`${name}-hero-${fraction}.png`)});}
 r.deep=[];for(const f of [.25,.55,.85]){await page.evaluate(f=>scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*f,behavior:'instant'}),f);await page.waitForTimeout(240);r.deep.push(await page.evaluate(snapshot));if(mode==='desktop'||mode==='phone')await page.screenshot({path:path.join(out,`${name}-deep-${f}.png`)});}
 if(js){
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(200);
  r.keyboard=[];for(let i=0;i<14;i++){await page.keyboard.press('Tab');await page.waitForTimeout(800);r.keyboard.push(await page.evaluate(()=>{const e=document.activeElement,b=e.getBoundingClientRect(),s=getComputedStyle(e);let opacity=1;for(let a=e;a;a=a.parentElement)opacity*=Number(getComputedStyle(a).opacity);return {tag:e.tagName,text:(e.textContent||e.getAttribute('aria-label')||'').trim().slice(0,70),href:e.getAttribute('href'),visible:b.bottom>0&&b.top<innerHeight&&b.right>0&&b.left<innerWidth,opacity,outline:s.outline,inert:Boolean(e.closest('[inert]'))};}));}
  if(mode==='desktop'||mode==='reduced'){
   await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.mouse.move(20,200);await page.waitForTimeout(200);const a=await page.evaluate(snapshot);const left=await page.screenshot({path:path.join(out,name+'-pointer-left.png')});await page.mouse.move(width-20,400);await page.waitForTimeout(200);const b=await page.evaluate(snapshot);const right=await page.screenshot({path:path.join(out,name+'-pointer-right.png')});r.pointer={before:a.layers,after:b.layers,pixelsChanged:!left.equals(right)};
  }
  if(reader){
   r.disclosures=[];
   for(let i=0;i<3;i++){
    const btn=page.locator('.blog-toggle-btn').nth(i);await btn.focus();await page.keyboard.press('Enter');await page.waitForTimeout(650);await page.evaluate(()=>window.__timTypesetQueue||Promise.resolve());
    const state=await btn.evaluate(e=>{const c=e.closest('.blog-card').querySelector('.blog-content');return {title:e.textContent.trim(),expanded:e.getAttribute('aria-expanded'),controls:e.getAttribute('aria-controls'),inert:c.inert,ariaHidden:c.getAttribute('aria-hidden'),height:c.getBoundingClientRect().height,text:c.textContent,math:c.querySelectorAll('mjx-container').length,mathErrors:c.querySelectorAll('mjx-merror,[data-mjx-error]').length,equations:[...c.querySelectorAll('.blog-equation')].map(q=>({width:q.clientWidth,scrollWidth:q.scrollWidth,overflow:getComputedStyle(q).overflowX})),documentWidth:document.documentElement.scrollWidth,viewport:innerWidth};});
    state.textHash=crypto.createHash('sha256').update(state.text).digest('hex');delete state.text;
    await btn.evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(220);if(mode==='desktop'||mode==='phone')await page.screenshot({path:path.join(out,`${name}-note-${i}-open.png`)});
    if(i===1){
     r.articleDeep=[];for(const f of [.3,.6,.9]){await btn.evaluate((e,f)=>{const c=e.closest('.blog-card');scrollTo({top:c.getBoundingClientRect().top+scrollY+c.offsetHeight*f,behavior:'instant'});},f);await page.waitForTimeout(250);r.articleDeep.push(await page.evaluate(snapshot));if(mode==='desktop'||mode==='phone')await page.screenshot({path:path.join(out,`${name}-article-${f}.png`)});}
     if(mode==='desktop'){await page.setViewportSize({width:390,height:844});await page.waitForTimeout(750);r.resizeWhileOpen=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,open:document.querySelectorAll('.blog-card.expanded').length,math:document.querySelectorAll('mjx-container').length,layers:document.querySelectorAll('.stochastic-layer[data-depth]').length}));await page.screenshot({path:path.join(out,name+'-resized-open.png')});await page.setViewportSize({width,height});await page.waitForTimeout(750);}
    }
    const equation=page.locator('.blog-card').nth(i).locator('.blog-equation');let wide=-1;for(let j=0;j<await equation.count();j++)if(await equation.nth(j).evaluate(e=>e.scrollWidth>e.clientWidth+2)){wide=j;break;}
    if(wide>=0){const e=equation.nth(wide);await e.evaluate(e=>{e.scrollLeft=e.scrollWidth;});state.equationScrolled=await e.evaluate(e=>({left:e.scrollLeft,max:e.scrollWidth-e.clientWidth}));}
    await btn.focus();await page.keyboard.press('Enter');await page.waitForTimeout(650);state.closed=await btn.evaluate(e=>{const c=e.closest('.blog-card').querySelector('.blog-content');return {expanded:e.getAttribute('aria-expanded'),height:c.getBoundingClientRect().height,inert:c.inert,ariaHidden:c.getAttribute('aria-hidden')};});r.disclosures.push(state);
   }
  } else {
   r.anchors=[];for(const id of ['about','projects','notes','academic-background','modules']){await page.locator(`.index-link[href="#${id}"]`).click();await page.waitForTimeout(1000);r.anchors.push(await page.evaluate(id=>({id,top:document.getElementById(id).getBoundingClientRect().top,headerBottom:document.querySelector('.index').getBoundingClientRect().bottom,hash:location.hash}),id));}
   const reset=page.locator('.path-reset');await reset.scrollIntoViewIfNeeded();await reset.focus();await page.waitForTimeout(800);const before=await page.locator('[data-path-line]').getAttribute('d');await reset.press('Enter');await page.waitForTimeout(500);r.newPath={changed:before!==await page.locator('[data-path-line]').getAttribute('d'),status:await page.locator('.path-status').textContent()};
   const module=page.locator('.module-btn').first();await module.click();await page.waitForTimeout(550);r.module=await module.evaluate(e=>({expanded:e.getAttribute('aria-expanded'),height:e.nextElementSibling.getBoundingClientRect().height}));await module.focus();await page.keyboard.press('Enter');await page.waitForTimeout(550);r.module.closed=await module.evaluate(e=>e.getAttribute('aria-expanded'));
  }
 }
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,name+'-closing.png')});r.finalWidth=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));
 if(mode==='desktop'){const urls=await page.locator('a[href]').evaluateAll(as=>[...new Set(as.map(a=>a.href))]);r.localLinks=[];for(const href of urls.filter(x=>x.startsWith(base))){const u=new URL(href);u.hash='';const q=await page.request.head(u.href);r.localLinks.push({url:u.href,status:q.status()});}}
 r.resources=[...new Set(r.resources)];reports.push(r);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify({name,errors:r.errors,failed:r.failed,httpErrors:r.httpErrors,width:r.finalWidth,math:r.initial.math,notes:r.initial.notes,mathErrors:r.initial.mathErrors,keyboardIssues:r.keyboard?.filter(x=>!x.visible||x.opacity<.85||x.inert),oldArt:r.resources.filter(x=>x.includes('atelier')),newPath:r.newPath}));await page.close();
}
await browser.close();
